<?php

return [
    'permissions' => [
        'Site',
        'ContactPerson',
        'Server',
        'VM',
        'NAS',
        'SecurepointUTM',
        'Router',
        'Network',
        'NetworkSwitch',
        'Wifi',
        'Accesspoint',
        'Computer',
        'IoTDevice',
        'Machine',
        'OtherClient',
        'Printer',
        'ADDomain',
        'ADUser',
        'ADGroup',
        'PhoneSystem',
        'Phone',
        'DECT',
        'LoginGeneral',
        'LoginNAS',
        'LoginWebsite',
        'LoginRecorder',
        'SecurepointUMA',
        'Mailbox',
        'Recorder',
        'Camera',
        'LicenseSoftware',
        'LicenseWindows',
        'LicenseAccess',
        'FTPServer',
        'DynDNS',
        'File',
        'Radiocenter',
        'Ups',
        'InternetConnection',
        'Domain',
        'Backup'
    ],

    /*
     * Whitelist für den Papierkorb: URL-Slug => [Model-Klasse, Anzeigename].
     * Nur Models mit customer_id und SoftDeletes aufnehmen.
     */
    'trashables' => [
        'site' => [\App\Models\Site::class, 'Standort'],
        'contactperson' => [\App\Models\ContactPerson::class, 'Ansprechpartner'],
        'server' => [\App\Models\Server::class, 'Server'],
        'vm' => [\App\Models\VM::class, 'VM'],
        'nas' => [\App\Models\NAS::class, 'NAS'],
        'securepointutm' => [\App\Models\SecurepointUTM::class, 'Securepoint UTM'],
        'securepointuma' => [\App\Models\SecurepointUMA::class, 'Securepoint UMA'],
        'router' => [\App\Models\Router::class, 'Router'],
        'network' => [\App\Models\Network::class, 'Netzwerk'],
        'networkswitch' => [\App\Models\NetworkSwitch::class, 'Switch'],
        'wifi' => [\App\Models\Wifi::class, 'WLAN'],
        'accesspoint' => [\App\Models\Accesspoint::class, 'Accesspoint'],
        'computer' => [\App\Models\Computer::class, 'Computer'],
        'iotdevice' => [\App\Models\IoTDevice::class, 'IoT-Gerät'],
        'machine' => [\App\Models\Machine::class, 'Maschine'],
        'otherclient' => [\App\Models\OtherClient::class, 'Sonstiger Client'],
        'printer' => [\App\Models\Printer::class, 'Drucker'],
        'addomain' => [\App\Models\ADDomain::class, 'AD-Domäne'],
        'aduser' => [\App\Models\ADUser::class, 'AD-Benutzer'],
        'adgroup' => [\App\Models\ADGroup::class, 'AD-Gruppe'],
        'phonesystem' => [\App\Models\PhoneSystem::class, 'TK-Anlage'],
        'phone' => [\App\Models\Phone::class, 'Telefon'],
        'dect' => [\App\Models\DECT::class, 'DECT'],
        'logingeneral' => [\App\Models\LoginGeneral::class, 'Login Allgemein'],
        'loginnas' => [\App\Models\LoginNAS::class, 'Login NAS'],
        'loginwebsite' => [\App\Models\LoginWebsite::class, 'Login Webseite'],
        'loginrecorder' => [\App\Models\LoginRecorder::class, 'Login Recorder'],
        'mailbox' => [\App\Models\Mailbox::class, 'Postfach'],
        'recorder' => [\App\Models\Recorder::class, 'Recorder'],
        'camera' => [\App\Models\Camera::class, 'Kamera'],
        'licensesoftware' => [\App\Models\LicenseSoftware::class, 'Software-Lizenz'],
        'licensewindows' => [\App\Models\LicenseWindows::class, 'Windows-Lizenz'],
        'licenseaccess' => [\App\Models\LicenseAccess::class, 'CAL-Lizenz'],
        'ftpserver' => [\App\Models\FTPServer::class, 'FTP-Server'],
        'dyndns' => [\App\Models\DynDNS::class, 'DynDNS'],
        'radiocenter' => [\App\Models\Radiocenter::class, 'Funkzentrale'],
        'ups' => [\App\Models\Ups::class, 'USV'],
        'internetconnection' => [\App\Models\InternetConnection::class, 'Internet-Anschluss'],
        'domain' => [\App\Models\Domain::class, 'Domain'],
        'backup' => [\App\Models\Backup::class, 'Backup'],
    ],
];
