<?php

return [
    'permissions' => [
        'Site',
        'Contactperson',
        'Server',
        'VM',
        'NAS',
        'SecurepointUTM',
        'Router',
        'Network',
        'Wifi',
        'Computer',
        'Printer',
        'ADDomain',
        'ADUser',
        'ADGroup',
        'PhoneSystem',
        'Phone',
        'DECT',
        'LoginGeneral',
        'LoginNAS',
        'LoginWebsite',
        'SecurepointUMA',
        'Mailbox',
        'Recorder',
        'Camera',
        'LicenseSoftware',
        'LicenseWindows',
        'LicenseAccess',
        'FTPServer',
        'DynDNS',
        'File'
    ],
];
